Remove not needed statements that are also stored in SqlStatementRepository
techdivision/import-product-url-rewrite pull request #20
Opened 2020-03-11 15:08 UTC by sippsolutions

Remove not needed statements that are also stored in SqlStatementRepository

2020-03-11 15:08 UTC, sippsolutions commented
@wagnert

2020-03-12 17:49 UTC, wagnert requested changes
Beside the comments in the code, it would be nice, if you can also delete the appropriate constants in the class, if not needed anymore.

2020-03-12 17:49 UTC, wagnert commented on src/Utils/SqlStatementKeys.php
> -        SqlStatementKeys::CREATE_URL_REWRITE_PRODUCT_CATEGORY =>
This is not available in 'TechDivision\Import\Utils\SqlStatements' and can therefor not been deleted.

2020-03-12 17:49 UTC, wagnert commented on src/Utils/SqlStatementKeys.php
> -        SqlStatementKeys::UPDATE_URL_REWRITE_PRODUCT_CATEGORY =>
This is not available in 'TechDivision\Import\Utils\SqlStatements' and can therefor not been deleted.

2020-03-12 17:49 UTC, wagnert commented on src/Utils/SqlStatementKeys.php
> -        SqlStatementKeys::DELETE_URL_REWRITE_PRODUCT_CATEGORY =>
This is not available in 'TechDivision\Import\Utils\SqlStatements' and can therefor not been deleted.

2020-03-12 17:49 UTC, wagnert commented on src/Utils/SqlStatementKeys.php
> -        SqlStatementKeys::URL_REWRITE_PRODUCT_CATEGORY =>
This is not available in 'TechDivision\Import\Utils\SqlStatements' and can therefor not been deleted.

2020-03-12 17:49 UTC, wagnert commented on src/Utils/SqlStatementKeys.php
> -        SqlStatementKeys::URL_REWRITES_BY_SKU =>
This is not available in 'TechDivision\Import\Utils\SqlStatements' and can therefor not been deleted.

2020-03-12 17:49 UTC, wagnert commented on src/Utils/SqlStatementKeys.php
> -        SqlStatementKeys::URL_REWRITE_PRODUCT_CATEGORIES_BY_SKU =>
This is not available in 'TechDivision\Import\Utils\SqlStatements' and can therefor not been deleted.

2020-03-12 18:56 UTC, sippsolutions commented
Hi @wagnert,

the deleted code seems to be copied from the SqlStatementRepository class.
The constructor tries to assign data to a variable called "preparedStatements" that's not available in SqlStatementKeys classes, but is available in Repositories.
Are you sure the mentioned keys are still needed?
If they are needed, a $preparedStatements private variable should be declared, otherwise the code should be removed (and the constants you mentioned aswell).

2020-03-13 14:27 UTC, wagnert commented
Will be fixed with the next release.

2020-03-13 14:27 UTC, closed without merging